import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/soner';
import { AuthProvider } from '@/context/AuthContext';

// const inter = Inter({
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--inter-font',
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body>
          {/* <AuthProvider> */}
          <main className="flex h-screen">{children}</main>
          <Toaster />
          {/* </AuthProvider> */}
        </body>
      </html>
    </AuthProvider>
  );
}
